import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/keybindings.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
dynamic_title = true

[window.dimensions]
columns = 120
lines = 30
