= Anish's Dotfiles
Anish Govind <anish@anishgovind.com>
v1.2, 2024-03-13
:toc:
:homepage: https://anishgovind.com

*To Dos*

* Bake my zsh configuration
* Bake my tmux configuration
* Bake my nvim configuration

== Installation

[,bash]
----
git clone https://github.com/anishg24/.dotfiles ~/.dotfiles
cd ~/.dotfiles
./install
----

== Executables

The following executables can be installed to `+~/.dotfiles/bin/+` and sourced
by `+~/.zshrc+`:

* nvim
* fzf
* zoxide
* lsd
* bat

To install these executables, I assume you're on an x86 GNU/Linux OS, then you can
run:

[,bash]
----
~/.dotfiles/scripts/install/install.sh <exe_name>
----

== Docker

A Docker container containing my command-line dotfile changes is planned to be developed.

== Modifications

This repository uses https://github.com/anishathalye/dotbot[dotbot] which not only generates
symlinks but also can run arbitrary shell commands to setup more things (like installing 
executables) and cleanup any dead symlinks in case there's an issue. 

On top of all of this, https://github.com/anishathalye/dotbot[dotbot] is incredibly portable
and bootstraps itself, making it desirable for use across multiple systems.
