alias vim="nvim"
alias cat="bat --paging=never"
alias ls="lsd"
alias l="ls -al"
alias clear="clear -x"
alias rm="rm -I"
alias zshconf="$EDITOR ~/.zshrc"
alias hyprconf="$EDITOR $HOME/.config/hypr/hyprland.conf"
alias setup="source ./setup_env.sh"
