export PATH="$HOME/.dotfiles/bin:$PATH"
export EDITOR="nvim"
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZSH_TMUX_FIXTERM=true
export GPG_TTY=$(tty)
export BAT_THEME="base16"
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=dark
--color=fg:-1,bg:-1,hl:#c678dd,fg+:#ffffff,bg+:#4b5263,hl+:#d858fe
--color=info:#98c379,prompt:#61afef,pointer:#be5046,marker:#e5c07b,spinner:#61afef,header:#61afef
'

host_sh_file=$HOME/.dotfiles/config/zshrc/$(hostname)/env.sh

# Run code before using oh-my-zsh (config for modules)
source $host_sh_file 0 || (mkdir -p $(dirname $host_sh_file) && touch $host_sh_file)

source ~/.dotfiles/config/zshrc/antigen.zsh

antigen use oh-my-zsh

COMPLETION_WAITING_DOTS="..."
ZVM_INIT_MODE="sourcing"

antigen bundle git
antigen bundle archlinux
antigen bundle tmux
antigen bundle battery
antigen bundle fzf
antigen bundle colored-man-pages
antigen bundle jsontools
antigen bundle zoxide
antigen bundle Aloxaf/fzf-tab
antigen bundle changyuheng/zsh-interactive-cd
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme romkatv/powerlevel10k

antigen apply

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#eval "$(ntfy shell-integration --foreground-too)"
#export AUTO_NTFY_DONE_IGNORE="$AUTO_NTFY_DONE_IGNORE vim nvim hx screen tmux ta ssh mosh perlmutter_pass"

source $ZSH/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh

# Zoxide init
# compinit
eval "$(zoxide init --cmd cd zsh)"

# Run code after setting up oh-my-zsh
source ~/.dotfiles/config/zshrc/$(hostname)/env.sh 1

export QSYS_ROOTDIR="/home/anish/.cache/paru/clone/quartus-free/pkg/quartus-free-quartus/opt/intelFPGA/23.1/quartus/sopc_builder/bin"
